"""Arquivo de inicializaçao do modulo usecases"""
from .starwars_characters_colector_interface import StarwarsCharactersColectorInterface
from .register_user_interface import RegisterUserInterface
from .hash_password_interface import HashPasswordInterface
from .get_user_interface import GetUserInterface
from .authentication_interface import AuthenticationInterface
from .authorization_interface import AuthorizationInterface
from .register_character_interface import RegisterCharacterInterface
from .get_characters_interface import GetCharacterInterface
