"""Arquivo de inicializaçao do modulo composers"""
from .starwars_characters_colector_composer import starwars_characters_colector_composer
from .register_user_composer import register_user_composer
from .get_user_composer import get_user_composer
from .get_users_composer import get_users_composer
from .authentication_composer import authentication_composer
from .register_character_composer import register_character_composer
from .get_character_composer import get_character_composer
from .update_user_composer import update_user_composer
